### ISSUE TITLE
[Feature/Recommendation] API Improvements

### ISSUE THREAD

**Issue by ghost** [phazelift/types.js#4]
### What needs improvement?
A more composable API that allows better type composition and custom type validation/conversion.

### How can it be improved?
For primitive types (`number|boolean|string|...`) you can replace `[action][type]()` with `[type].[action]()` (possibly with an `or(type)` method for unions); for generic types such as arrays, the same thing could be implemented as `[genericType](...types).[action]()` (functions would be a special case). Custom types could be implemented by extending a base type via `[BaseType].extend(propertiesAndMethodsFactory)` (you obviously don't have to use that long parameter name). Here's an example:
```js
// Here's a type alias:
const Matrix = Types.Array(Types.Array(Types.Number));
// Is this a matrix? (using nested array syntax with trailing comma)
console.log(Matrix.is([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])); //=> true

// A utility function:
function hasNoFloatingPoint(x) {
    return x % 1 == 0 // x % 1 gets the floating part from the original value, so 3.14 % 1 = 0.14;
}

// Here's a custom type from `Types.Number` that validates integer types:
const Int = Types.Number.extend(base => ({
    is(x) {
        return base.is(x) && hasNoFloatingPoint(x);
    },
    //...
}));
```
### My remarks.

This is an idea that I had when I just ran into this package while looking for a static typing algorithm this evening for my very own virtual machine; I may use this library for my project (the rest is home grown except the parser)!

**Comment by phazelift** [comment]
Hi Ivan,

Thank you for your email and suggestions. I am extremely busy lately and
will have to look into this later. I'm not sure whether I would like to
change the API of types.js. It is now almost 8 years ago I wrote this and I
would definitely write it all differently today. So it might be better to
take the best ideas of it and put it in a new project, not sure. It's MIT
so you can use whatever you like and need :)

Please share me a link to your project if it's open source, it sounds
interesting!

Best,
Dennis
